MERGE OPER:
Elena-Lou/ft_irc pull request #28
Opened 2023-06-10 22:04 UTC by Elena-Lou

Author's registration, nb of params and password are checked.

switch cases are set and so is RPL if command is successfull.

The last check, the client is not authorised to become Oper depends on
MODE command and will be completed later

Close #5 

Co-authored-by: aweaver [aweaver@student.42.fr](mailto:aweaver@student.42.fr)
Co-authored-by: elouisia [elouisiade@live.fr](mailto:elouisiade@live.fr)

2023-06-11 07:01 UTC, AdrianWeaver requested changes
Nice but a few things are missing !

2023-06-11 07:01 UTC, AdrianWeaver commented on Oper.cpp
> +	this->_author->writeRPLToClient(this->_server,
The RPL sent to the user confirms to him/her that he is oper.
But the server has no way of knowing who is operator right now. 

I don't understand the scope of this command if this is to set a chanOp or a ServerOp or something...

Have a look at how the Channel handles Operators !

2023-06-12 14:06 UTC, Elena-Lou commented on Oper.cpp
> +}
Fool of a Took !

2023-06-12 14:07 UTC, Elena-Lou commented on Oper.cpp
> +	}
It is not called yet because we don't have the modes and hence a way to check if a new chanOp can be set for this channel

2023-06-12 16:07 UTC, Elena-Lou commented on Oper.cpp
> +		RPL_YOUROPER, MSG_YOUROPER);
Did I write ERR_YOUROPER ? I am confused x]
Otherwise I agree with you regarding the spelling shortcut

2023-06-12 17:26 UTC, AdrianWeaver approved these changes
YOUROPER should still be YOUREOPER (as in you are not your).

Some indentations are spaces instead of tabs but it's fine.
Thanks !

2023-06-12 17:26 UTC, merged